In [232]:
import math as mt
import sympy as sp
from IPython.display import display, Math
import numpy as np
from math import exp
from sympy.parsing.sympy_parser import parse_expr


# Soluciones Computacionales a Problemas de Ingeniería IST4360




*   Estudiantes:
*   Código:


Dado el problema de valor inicial
$$y'=\frac{2}{t}y+t^2e^t,\, 1\leq t\leq2,\, y(1)=0,$$
con solución exacta $y(t)=t^2(e^t-e)$:



1.   Encuentre $n$ para el método de Taylor tal que el error absoluto sea del orden de $10^{-6}$. Use $h=0.1$
2.   Use los valores generados en el inciso anterior para el $n$ encontrado y una aproximación de la forma $be^{ax}$ por mínimos cuadrados para aproximar $y$ en los siguientes valores, compare con los valores reales de $y$.

  *   $y(1.04)$
  *   $y(1.55)$
  *   $y(1.97)$
















In [233]:
# Definimos una función que nos permita iterar nuestro método y obtener Tn
def Tn(f,n,h):
    df = f
    T = f
    for i in range(1,n):
        df = sp.diff(df,t).subs(dy,f)
        T += df*h**i/mt.factorial(i+1)
    return T

In [234]:
# Definimos nuestras funciones y variables como expresiones matemáticas
t = parse_expr("t")
yt = parse_expr("y(t)")
dy = sp.diff(yt,t)
f = parse_expr("(2/t*y(t))+t**2*exp(t)")

In [235]:
# Parametros iniciales, paso y número de pasos
h = 0.1
a = 1
b = 2
N = int((b-a)/h)
n_max = 5
W = np.empty((n_max, N+1))

# Evaluamos nuestra función
for ni in range(1, n_max+1):
    wi = 0
    ti = 1
    W[ni-1,0] = ni
    for i in range(1,N+1):
        wi += h*(float(Tn(f,ni,h).subs({yt:wi, t:ti}).evalf()))
        W[ni-1, i] = wi
        ti += h

In [236]:
# Calculamos el error de nuestro método
y = lambda t: (t**2)*(mt.exp(t)-mt.exp(1))
errors = np.abs(y(2)- W[:,-1])
print(errors)

[3.28486143e+00 2.13102599e-01 8.07810240e-03 2.28913877e-04
 5.14326115e-06]


In [237]:
W[4].reshape((-1,1))

array([[ 5.        ],
       [ 0.34591971],
       [ 0.86664215],
       [ 1.60721441],
       [ 2.62035853],
       [ 3.96766484],
       [ 5.72095956],
       [ 7.96387089],
       [10.79362135],
       [14.32307738],
       [18.68309194]])

In [238]:
np.linspace(a,b,N+1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [239]:
X = np.zeros((N+1,2))
X[:,1] = 1
X[:,0] = np.linspace(a,b,N+1)
y = np.zeros(((N+1),1))
y[1:] = np.log(W[4,1:].reshape((-1,1)))
y = y[1:]
X = X[1:]
print(y)

[[-1.06154858]
 [-0.14312913]
 [ 0.4745025 ]
 [ 0.96331115]
 [ 1.37817772]
 [ 1.74413655]
 [ 2.07491517]
 [ 2.37895534]
 [ 2.66187204]
 [ 2.92761894]]


In [240]:
beta = np.linalg.inv(X.T@X)@X.T@y
beta

array([[ 4.16730612],
       [-5.11944332]])

In [241]:
a = beta[0]
b = np.exp(beta[1])
print(a)
print(b)

[4.16730612]
[0.00597935]


In [242]:
def funcion(t):
    return b * np.exp(a * t)

def y_exact(t):
    return t**2 * (np.exp(t) - np.exp(1))

t_values = [1.04, 1.55, 1.97]

y_approx = [funcion(t) for t in t_values]
print(f"valores aproximados de la funcion:")
for i in y_approx:
    print(i)

y_real = [y_exact(t) for t in t_values]
print("valores aproximados de la funcion real: ")
for i in y_real:
    print(i)

print("\nErrores absolutos:")
for i in range(len(y_approx)):
    error = abs(y_approx[i] - y_real[i])
    print(f"Error en t = {t_values[i]}: {error}")

valores aproximados de la funcion:
[0.4559168]
[3.81858972]
[21.98036909]
valores aproximados de la funcion real: 
0.11998749706134393
4.788635020801403
17.279298435557664

Errores absolutos:
Error en t = 1.04: [0.3359293]
Error en t = 1.55: [0.9700453]
Error en t = 1.97: [4.70107066]


**Nota:** Por favor incluir en el archivo que contenga la solución los script, funciones, gráficas, código y cualquier otro elemento utilizado. No coloque respuestas sin justificación, muestre todo los desarrollos.

**Recuerde:** En este curso no se tolerará el plagio. Sin excepción, en caso de presentarse esta situación, a los estudiantes involucrados se les iniciará proceso de investigación, y se actuará en conformidad con el Reglamento de Estudiantes de la Universidad del Norte. El plagio incluye: usar contenidos sin la debida referencia, de manera literal o con mínimos cambios que no alteren el espíritu del texto/código; adquirir con o sin intención, trabajos de terceros y presentarlos parcial o totalmente como propios; presentar trabajos en grupo donde alguno de los integrantes no trabajó o donde no se hubo trabajo en equipo demostrable; entre otras situaciones definidas en el manual de fraude académico de la Universidad del Norte ([pdf](https://guayacan.uninorte.edu.co/normatividad_interna/upload/File/Guia_Prevencion_Fraude%20estudiantes(5).pdf)).